# Generated by Django 4.2.16 on 2024-11-05 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiveDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('continent', models.CharField(max_length=500)),
                ('country', models.CharField(max_length=500)),
                ('link', models.URLField()),
                ('dive_types', models.TextField()),
                ('logged_species', models.IntegerField()),
            ],
        ),
    ]
